spring.application.name=bank-api

# MongoDB Atlas Connection
spring.mongodb.uri=mongodb+srv://bankAdmin:bankPass1@bankappcluster.iakzwmk.mongodb.net/?appName=bankAppCluster

spring.mongodb.database=bank_db

# Optional: Port configuration (default is 8080)
server.port=8080